FROM python:3.11-slim

WORKDIR /app

COPY services/circulation/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY shared ./shared
COPY services/circulation ./services/circulation

ENV PYTHONPATH=/app:/app/shared/gen
ENV PORT=50051

WORKDIR /app/services/circulation
EXPOSE 50051

CMD ["python", "app.py"]